export const APP_NAME = 'MarketPro'
export const APP_TAGLINE = 'Smart POS & inventory for modern market shops'

export const NAV = {
  DASHBOARD: 'Dashboard',
  POS: 'POS',
  INVENTORY: 'Inventory',
  INVENTORY_CATEGORIES: 'Categories',
  INVENTORY_SUPPLIERS: 'Suppliers',
  REPORTS: 'Reports',
  REPORTS_PRODUCTS: 'Top Products',
  REPORTS_STAFF: 'Staff',
  STAFF: 'Staff',
  STAFF_SHIFTS: 'Shifts',
  AI: 'AI',
  SETTINGS: 'Settings',
} as const

export const AUTH = {
  SIGN_IN_TITLE: 'Welcome back',
  SIGN_IN_DESCRIPTION: 'Sign in to your MarketPro account',
  SIGN_UP_TITLE: 'Create your account',
  SIGN_UP_DESCRIPTION: 'Get started with MarketPro today',
  SIGN_IN: 'Sign in',
  SIGN_UP: 'Create account',
  SIGN_OUT: 'Sign out',
  SIGNING_IN: 'Signing in…',
  SIGNING_UP: 'Creating account…',
  SIGN_IN_GOOGLE: 'Continue with Google',
  SIGN_UP_GOOGLE: 'Sign up with Google',
  SIGN_IN_ERROR: 'Invalid email or password.',
  SIGN_UP_ERROR: 'Could not create account. Please try again.',
  EMAIL_LABEL: 'Email',
  PASSWORD_LABEL: 'Password',
  NAME_LABEL: 'Full name',
  EMAIL_PLACEHOLDER: 'you@example.com',
  NAME_PLACEHOLDER: 'Ada Okafor',
  CHECK_EMAIL_TITLE: 'Check your email',
  CHECK_EMAIL_DESCRIPTION: 'We sent a verification link to your email. Click it to activate your account.',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  NO_ACCOUNT: "Don't have an account?",
  ONBOARDING_TITLE: 'Set up your shop',
  ONBOARDING_DESCRIPTION: 'Almost done. Give your shop a name to get started.',
  SHOP_NAME_LABEL: 'Shop name',
  SHOP_NAME_PLACEHOLDER: 'e.g. Mama Nkechi Supermarket',
  CREATE_SHOP: 'Create shop',
  CREATING_SHOP: 'Creating shop…',
} as const

export const TEAM = {
  TITLE: 'Team',
  DESCRIPTION: 'Manage staff members and their roles.',
  ADD_MEMBER: 'Add staff',
  INVITE_TITLE: 'Add a staff member',
  INVITE_EMAIL: 'Email address',
  INVITE_NAME: 'Full name',
  INVITE_ROLE: 'Role',
  INVITE_SUBMIT: 'Add staff',
  INVITE_SUBMITTING: 'Adding…',
  EMPTY: 'No staff members yet.',
  ROLE_OWNER: 'Owner',
  ROLE_MANAGER: 'Manager',
  ROLE_ACCOUNTANT: 'Accountant',
  ROLE_INVENTORY_MANAGER: 'Inventory Manager',
  ROLE_CASHIER: 'Cashier',
  REMOVE: 'Remove',
  REMOVE_CONFIRM: 'Remove this staff member?',
  CHANGE_ROLE: 'Change role',
} as const


export const ERRORS = {
  GENERIC: 'Something went wrong. Please try again.',
  UNAUTHORIZED: 'You are not authorized to perform this action.',
  NOT_FOUND: 'The requested resource was not found.',
  VALIDATION: 'Please check your input and try again.',
} as const

export const OFFLINE = {
  TITLE: 'You are offline',
  DESCRIPTION: 'MarketPro is running in offline mode. Some features are limited.',
  BANNER: 'No internet connection — working offline',
} as const

export const LANDING = {
  HERO_TITLE: 'The smarter way to run your shop',
  HERO_SUBTITLE: 'Fast POS, real-time inventory, and AI-powered insights — built for Nigerian supermarkets and market shops.',
  HERO_CTA_PRIMARY: 'Start for free',
  HERO_CTA_SECONDARY: 'See features',
  PREVIEW_TITLE: 'See MarketPro in action',
  PREVIEW_SUBTITLE: 'Real screens from the app — no mockups, no smoke and mirrors.',
  CTA_DASHBOARD: 'Go to Dashboard',
  FEATURES_TITLE: 'Everything your shop needs',
  FEATURES_SUBTITLE: 'From checkout to close of business, MarketPro keeps you in control.',
  PRICING_TITLE: 'Simple, honest pricing',
  PRICING_SUBTITLE: 'Start free, upgrade as you grow. No hidden fees.',
  FAQ_TITLE: 'Frequently asked questions',
  CONTACT_TITLE: 'Get in touch',
  CONTACT_SUBTITLE: 'We are here to help. Reach out anytime.',
  CONTACT_EMAIL: 'bestolumese@gmail.com',
  CONTACT_WHATSAPP: '+2348136345358',
  FOOTER_TAGLINE: 'Built for Nigerian market shops.',
  FOOTER_RIGHTS: `© ${new Date().getFullYear()} MarketPro. All rights reserved.`,
} as const

export const FEATURE_LIST = [
  {
    title: 'Fast Checkout',
    description: 'Ring up sales in seconds. Supports cash, card, and bank transfer.',
  },
  {
    title: 'Smart Inventory',
    description: 'Track stock in real time. Get low-stock alerts before you run out.',
  },
  {
    title: 'Sales Reports',
    description: 'Daily, weekly, and monthly reports. Know your best sellers at a glance.',
  },
  {
    title: 'Staff Management',
    description: 'Set roles and permissions for admins, managers, and cashiers.',
  },
  {
    title: 'Works Offline',
    description: 'No internet? Keep selling. MarketPro syncs automatically when you are back online.',
  },
  {
    title: 'AI Insights',
    description: 'Get smart reorder suggestions and demand forecasts powered by Claude AI.',
  },
] as const

export const PRICING_LIST = [
  {
    name: 'Starter',
    price: 'Free',
    description: 'Perfect for small shops just getting started.',
    features: [
      'Up to 500 products',
      '2 staff accounts',
      'Basic reports',
      'POS & inventory',
    ],
    cta: 'Get started free',
    featured: false,
  },
  {
    name: 'Growth',
    price: '₦9,900/mo',
    description: 'For growing shops that need more power.',
    features: [
      'Unlimited products',
      'Unlimited staff',
      'Full reports & analytics',
      '50 AI queries/month',
    ],
    cta: 'Start Growth plan',
    featured: true,
  },
  {
    name: 'Pro',
    price: '₦19,900/mo',
    description: 'For shops that need everything.',
    features: [
      'Everything in Growth',
      'Unlimited AI queries',
      'WhatsApp receipts & alerts',
      'Priority support',
    ],
    cta: 'Start Pro plan',
    featured: false,
  },
] as const

export const INVENTORY = {
  TITLE: 'Inventory',
  DESCRIPTION: 'Manage your products, categories, and suppliers.',
  NEW_PRODUCT: 'Add product',
  EDIT_PRODUCT: 'Edit product',
  IMPORT: 'Import CSV',
  EXPORT_CSV: 'Export CSV',
  SEARCH_PLACEHOLDER: 'Search products...',
  FILTER_ALL_CATEGORIES: 'All categories',
  EMPTY: 'No products yet.',
  EMPTY_DESCRIPTION: 'Add your first product to get started.',
  EMPTY_SEARCH: 'No products match your search.',
  LOW_STOCK_TITLE: 'Low stock',
  LOW_STOCK_EMPTY: 'All products are well stocked.',
  DELETE_CONFIRM_TITLE: 'Delete product?',
  DELETE_CONFIRM_DESCRIPTION: 'This action cannot be undone.',
  STOCK_IN: 'In stock',
  STOCK_LOW: 'Low stock',
  STOCK_OUT: 'Out of stock',
  CATEGORIES_TITLE: 'Categories',
  CATEGORIES_DESCRIPTION: 'Manage product categories.',
  NEW_CATEGORY: 'Add category',
  EDIT_CATEGORY: 'Edit category',
  CATEGORY_PLACEHOLDER: 'e.g. Beverages',
  SEARCH_CATEGORIES: 'Search categories…',
  EMPTY_CATEGORIES: 'No categories yet.',
  DELETE_CATEGORY_TITLE: 'Delete category?',
  DELETE_CATEGORY_DESC: 'Products in this category will become uncategorized.',
  SUPPLIERS_TITLE: 'Suppliers',
  SUPPLIERS_DESCRIPTION: 'Manage your suppliers.',
  NEW_SUPPLIER: 'Add supplier',
  EDIT_SUPPLIER: 'Edit supplier',
  SEARCH_SUPPLIERS: 'Search suppliers…',
  EMPTY_SUPPLIERS: 'No suppliers yet.',
  DELETE_SUPPLIER_TITLE: 'Delete supplier?',
  DELETE_SUPPLIER_DESC: 'Products linked to this supplier will become unlinked.',
  BULK_TITLE: 'Import products',
  BULK_DESCRIPTION: 'Upload a CSV file to import multiple products at once.',
  BULK_DROP: 'Drop your CSV here, or click to browse',
  BULK_FORMAT: 'Columns: name, barcode, price, cost_price, stock, low_stock_at, category, expiry_date',
  BULK_IMPORTING: 'Importing...',
  BARCODE_PLACEHOLDER: 'Scan or enter barcode',
  BARCODE_SCAN: 'Scan',
  BARCODE_STOP: 'Stop scanning',
} as const

export const POS = {
  TITLE: 'Point of Sale',
  DESCRIPTION: 'Process sales and manage your shift.',
  OPEN_SHIFT: 'Open Shift',
  CLOSE_SHIFT: 'Close Shift',
  SHIFT_OPEN: 'Shift open',
  SHIFT_CLOSED: 'No shift open',
  OPENING_SHIFT: 'Opening shift…',
  CLOSING_SHIFT: 'Closing shift…',
  SEARCH_PLACEHOLDER: 'Search products…',
  EMPTY_PRODUCTS: 'No products found.',
  CART_EMPTY: 'Cart is empty',
  CART_EMPTY_HINT: 'Add products from the grid to get started.',
  CART_TITLE: 'Cart',
  SUBTOTAL: 'Subtotal',
  DISCOUNT: 'Discount',
  TOTAL: 'Total',
  PAY: 'Charge customer',
  PAYMENT_METHOD: 'Payment method',
  CASH: 'Cash',
  TRANSFER: 'Bank transfer',
  CARD: 'Card',
  CASH_TENDERED: 'Amount tendered',
  CHANGE: 'Change',
  CONFIRM_PAYMENT: 'Confirm payment',
  PROCESSING: 'Processing…',
  SALE_SUCCESS: 'Sale completed',
  SALE_ERROR: 'Failed to process sale. Please try again.',
  RECEIPT_TITLE: 'Receipt',
  PRINT: 'Print receipt',
  NEW_SALE: 'New sale',
  OFFLINE_BANNER: 'You are offline — only cash payments accepted.',
  OFFLINE_BLOCKED: 'Card and bank transfer require an internet connection.',
  TRANSFER_BANK: 'Bank',
  TRANSFER_ACCOUNT: 'Account number',
  TRANSFER_NAME: 'Account name',
  TRANSFER_AMOUNT: 'Amount',
  TRANSFER_SCAN: 'Scan to pay',
  TRANSFER_DONE: 'Payment received',
  DISCOUNT_LABEL: 'Discount (%)',
  OPEN_SHIFT_REQUIRED: 'Please open a shift before processing sales.',
  VOID: 'Void sale',
  VOID_CONFIRM: 'Are you sure you want to void this sale? Stock will be restored.',
  VOID_SUCCESS: 'Sale voided successfully.',
} as const

export const REPORTS = {
  TITLE: 'Reports',
  DESCRIPTION: 'Sales performance, top products, and staff analytics.',
  SUMMARY_TITLE: 'Sales Summary',
  PRODUCTS_TITLE: 'Top Products',
  STAFF_TITLE: 'Staff Performance',
  PROFIT_TITLE: 'Profit Overview',
  DATE_FROM: 'From',
  DATE_TO: 'To',
  PRESET_TODAY: 'Today',
  PRESET_WEEK: 'This week',
  PRESET_MONTH: 'This month',
  PRESET_LAST_MONTH: 'Last month',
  REVENUE: 'Revenue',
  COST: 'Est. cost',
  PROFIT: 'Est. profit',
  MARGIN: 'Margin',
  SALES_COUNT: 'Sales',
  UNITS_SOLD: 'Units sold',
  EXPORT_CSV: 'Export CSV',
  EXPORT_PDF: 'Export PDF',
  EXPORTING: 'Exporting…',
  NO_DATA: 'No data for this period.',
  RANK: '#',
  PRODUCT: 'Product',
  STAFF_MEMBER: 'Staff',
  TOTAL_SALES: 'Total sales',
  ITEMS_SOLD: 'Items sold today',
  LOW_STOCK: 'Low stock alerts',
  ACTIVE_STAFF: 'Active staff',
  SALES_TODAY: 'Revenue today',
  CHART_LABEL: 'Revenue (₦)',
} as const

export const SETTINGS = {
  TITLE: 'Settings',
  DESCRIPTION: 'Manage your shop profile, organization details, and team members.',
} as const

export const AI = {
  TITLE: 'AI Insights',
  DESCRIPTION: 'Ask questions, forecast demand, and get pricing suggestions powered by Claude.',
  TAB_CHAT: 'Ask AI',
  TAB_FORECAST: 'Demand Forecast',
  TAB_INSIGHTS: 'Insights',
  CHAT_PLACEHOLDER: 'Ask anything about your shop…',
  CHAT_EMPTY: 'Ask me anything about your sales or inventory. Try one of these:',
  THINKING: 'Thinking…',
  QUERY_ERROR: 'Failed to get a response. Please try again.',
  FORECAST: 'Forecast',
  ANALYSING: 'Analysing…',
  CURRENT_STOCK: 'Current stock',
  RESTOCK_QTY: 'Recommended restock',
  DAYS_UNTIL_STOCKOUT: 'Days until stockout',
  CONFIDENCE: 'Confidence',
  SUGGEST_PRICE: 'Suggest price',
  CURRENT_PRICE: 'Current price',
  SUGGESTED_PRICE: 'Suggested price',
  DETECT_ANOMALIES: 'Detect Anomalies',
  NO_ANOMALIES: 'No anomalies detected in recent sales. Everything looks normal.',
  ANOMALY_ERROR: 'Failed to run anomaly detection.',
  ANOMALIES_TITLE: 'Sales Anomalies',
  PRICING_TITLE: 'Pricing Suggestions',
  FORECAST_TITLE: 'Demand Forecast',
  FORECAST_DESCRIPTION: 'Select a product to get a restock prediction.',
  DIGEST_TITLE: 'Weekly Digest',
  DIGEST_DESCRIPTION: 'Generate a plain-English summary of your shop\'s performance this week.',
  GENERATE_DIGEST: 'Generate digest',
  GENERATING: 'Generating…',
  DIGEST_ERROR: 'Failed to generate digest.',
  QUOTA_LABEL: 'AI queries used',
} as const

export const BILLING = {
  TITLE: 'Billing',
  DESCRIPTION: 'Manage your subscription and plan.',
  CURRENT_PLAN: 'Current plan',
  PLAN_STARTER: 'Starter',
  PLAN_GROWTH: 'Growth',
  PLAN_PRO: 'Pro',
  STATUS_ACTIVE: 'Active',
  STATUS_PAST_DUE: 'Past due',
  STATUS_CANCELLED: 'Cancelled',
  STATUS_TRIALING: 'Trialing',
  UPGRADE_TO_GROWTH: 'Upgrade to Growth',
  UPGRADE_TO_PRO: 'Upgrade to Pro',
  UPGRADING: 'Redirecting to checkout…',
  CANCEL_SUBSCRIPTION: 'Cancel subscription',
  CANCELLING: 'Cancelling…',
  CANCEL_CONFIRM: 'Are you sure you want to cancel? Your current plan stays active until the end of your billing period, then your shop downgrades to Starter.',
  CANCEL_SUCCESS: 'Subscription cancelled. You are now on the Starter plan.',
  CANCEL_ERROR: 'Failed to cancel subscription. Please try again.',
  SUBSCRIBE_ERROR: 'Failed to start checkout. Please try again.',
  USAGE_PRODUCTS: 'Products used',
  USAGE_STAFF: 'Staff accounts',
  UNLIMITED: 'Unlimited',
  NEXT_BILLING: 'Next billing date',
  PLAN_FEATURES_STARTER: ['Up to 500 products', '2 staff accounts', 'Basic reports', 'POS & inventory'],
  PLAN_FEATURES_GROWTH: ['Unlimited products', 'Unlimited staff', 'Full reports & analytics', '50 AI queries/month'],
  PLAN_FEATURES_PRO: ['Everything in Growth', 'Unlimited AI queries', 'WhatsApp receipts & alerts', 'Priority support'],
  UPGRADE_PROMPT_TITLE: 'Upgrade your plan',
  UPGRADE_PROMPT_DESCRIPTION: 'This feature is not available on your current plan.',
} as const

export const STAFF = {
  TITLE: 'Staff',
  DESCRIPTION: 'View and manage your team.',
  MANAGE_TEAM: 'Manage team',
  MANAGE_TEAM_HINT: 'Invite new staff or change roles in Settings.',
  GO_TO_SETTINGS: 'Go to team settings',
  EMPTY: 'No staff members yet.',
  EMPTY_DESCRIPTION: 'Add staff from the team settings page.',
  SALES_COUNT: 'Sales',
  TOTAL_REVENUE: 'Revenue',
  SHIFT_COUNT: 'Shifts',
  VIEW_PROFILE: 'View profile',
  BACK_TO_STAFF: 'Back to staff',
  SALES_HISTORY: 'Sales history',
  SHIFT_HISTORY: 'Shift history',
  NO_SALES: 'No sales recorded yet.',
  NO_SHIFTS: 'No shifts recorded yet.',
} as const

export const SHIFTS = {
  TITLE: 'Shifts',
  DESCRIPTION: 'Open and close your shift. Track cash reconciliation.',
  OPEN_SHIFT: 'Open shift',
  CLOSE_SHIFT: 'Close shift',
  OPENING: 'Opening shift…',
  CLOSING: 'Closing shift…',
  OPENING_CASH_LABEL: 'Opening cash (₦)',
  OPENING_CASH_PLACEHOLDER: '0.00',
  CLOSING_CASH_LABEL: 'Closing cash in drawer (₦)',
  CLOSING_CASH_PLACEHOLDER: '0.00',
  NOTE_LABEL: 'Note (optional)',
  NOTE_PLACEHOLDER: 'Any discrepancy explanation…',
  CURRENT_SHIFT: 'Current shift',
  NO_OPEN_SHIFT: 'No shift open',
  NO_OPEN_SHIFT_HINT: 'Open a shift to start recording sales.',
  OPENED_AT: 'Opened',
  CLOSED_AT: 'Closed',
  OPENING_CASH: 'Opening cash',
  CLOSING_CASH: 'Closing cash',
  EXPECTED_CASH: 'Expected cash',
  DISCREPANCY: 'Discrepancy',
  STATUS_OPEN: 'Open',
  STATUS_CLOSED: 'Closed',
  HISTORY_TITLE: 'Shift history',
  HISTORY_EMPTY: 'No shifts recorded yet.',
  STAFF_FILTER: 'Filter by staff',
  ALL_STAFF: 'All staff',
  OPEN_SUCCESS: 'Shift opened successfully.',
  CLOSE_SUCCESS: 'Shift closed and reconciled.',
  OPEN_ERROR: 'Failed to open shift.',
  CLOSE_ERROR: 'Failed to close shift.',
  ALREADY_OPEN: 'You already have an open shift.',
  CONFIRM_CLOSE: 'Close shift',
  CONFIRM_CLOSE_DESCRIPTION: 'Enter the total cash in your drawer to reconcile.',
} as const

export const FAQ_LIST = [
  {
    question: 'Can I use MarketPro without internet?',
    answer: 'Yes. The POS and inventory work fully offline. Sales sync automatically when your internet is restored.',
  },
  {
    question: 'Do I need a card machine?',
    answer: 'No. MarketPro supports cash, bank transfer (USSD/mobile banking), and card. You bring your own terminal if needed.',
  },
  {
    question: 'How many staff can I add?',
    answer: 'Starter supports 2 staff accounts. Growth and Pro plans support unlimited staff with role-based access control.',
  },
  {
    question: 'Is my sales data safe?',
    answer: 'Yes. All data is encrypted and automatically backed up to secure cloud servers. You own your data.',
  },
  {
    question: 'Can I try it before paying?',
    answer: 'Yes. The Starter plan is completely free with no time limit. Upgrade only when you need more.',
  },
] as const
